### PR TITLE
Feature/weather app

### PR DESCRIPTION
**Pull request by pipe2442**
Weather App - Javascript 🚀🌞🌦

This branch was created to merge the weather app feature project using webpack for code optimization and consuming accuweather.com API for the weather requesting.

- Created src folder with index.js file.
- Configure Webpack to pack all our js into the dist folder with the main.js file.
- Created index.html just with body and content file.
- Developed modules to export project pages using different files.
- Create project styles with Bootstrap.
- Create request to fetch data to the Accuweather API.
- Create input field to search for specific city.
- Create function to return city name, country, date and weather specifications.
- Add project linters for better code styling.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑️🛑️🛑️🛑️**

Hello @pipe2442 
Great work on this project. The repo looks professional and I love the approach you took to build the solution.

However let's make changes and get it approved.

[REQUIRED]: The background image should change on each entry of new city
[REQUIRED]: There should be a toggle button to change from Celsius to Fahrenheit
[REQUIRED]: I am running the project by running index.html. Kindly modify script in package.json `"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
` to be able to run npm start.
[REQUIRED]: In apiRequest.js, add catch to be able to get errors of fetching the api.

That's it👍️

Make the requested changes and ask for another review 👍️

Happy coding💻️💻️💻️

**Comment by pipe2442** [comment]
The reqeusted changes were made:

- The background image change on each entry for a new city.
-  Celsius to Fahrenheit toggle button was created.
- .catch was added to API fetch.
- for the package.json you can just run the project in production mode with npm run build, and if you want to make changes live you can run npm run watch to enter the dev mode and see your changes immediately with live server.

**Comment by pipe2442** [comment]
The reqeusted changes were made:

- The background image change on each entry for a new city.
-  Celsius to Fahrenheit toggle button was created.
- .catch was added to API fetch.
- for the package.json you can just run the project in production mode with npm run build, and if you want to make changes live you can run npm run watch to enter the dev mode and see your changes immediately with live server.

**Comment by pipe2442** [comment]
The reqeusted changes were made:

- The background image change on each entry for a new city.
-  Celsius to Fahrenheit toggle button was created.
- .catch was added to API fetch.
- for the package.json you can just run the project in production mode with npm run build, and if you want to make changes live you can run npm run watch to enter the dev mode and see your changes immediately with live server.

**Comment by pipe2442** [comment]
The reqeusted changes were made:

- The background image change on each entry for a new city.
-  Celsius to Fahrenheit toggle button was created.
- .catch was added to API fetch.
- for the package.json you can just run the project in production mode with npm run build, and if you want to make changes live you can run npm run watch to enter the dev mode and see your changes immediately with live server.

**Review by taiwo2 — APPROVED** [review]
# STATUS: APPROVED 🎉 
@pipe2442, Great job done for implementing the suggested changes by the previous Code Reviewer. your Project approved, kindly merge and prepare for the next task. thanks

**Pull request merged**
